#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '../../Quartus_Files/soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'onchip_memory2_0', class 'altera_avalon_onchip_memory2'
 * The macros are prefixed with 'ONCHIP_MEMORY2_0_'.
 * The prefix is the slave descriptor.
 */
#define ONCHIP_MEMORY2_0_COMPONENT_TYPE altera_avalon_onchip_memory2
#define ONCHIP_MEMORY2_0_COMPONENT_NAME onchip_memory2_0
#define ONCHIP_MEMORY2_0_BASE 0x0
#define ONCHIP_MEMORY2_0_SPAN 65536
#define ONCHIP_MEMORY2_0_END 0xffff
#define ONCHIP_MEMORY2_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define ONCHIP_MEMORY2_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define ONCHIP_MEMORY2_0_CONTENTS_INFO ""
#define ONCHIP_MEMORY2_0_DUAL_PORT 0
#define ONCHIP_MEMORY2_0_GUI_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_INIT_CONTENTS_FILE soc_system_onchip_memory2_0
#define ONCHIP_MEMORY2_0_INIT_MEM_CONTENT 1
#define ONCHIP_MEMORY2_0_INSTANCE_ID NONE
#define ONCHIP_MEMORY2_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define ONCHIP_MEMORY2_0_RAM_BLOCK_TYPE AUTO
#define ONCHIP_MEMORY2_0_READ_DURING_WRITE_MODE DONT_CARE
#define ONCHIP_MEMORY2_0_SINGLE_CLOCK_OP 0
#define ONCHIP_MEMORY2_0_SIZE_MULTIPLE 1
#define ONCHIP_MEMORY2_0_SIZE_VALUE 65536
#define ONCHIP_MEMORY2_0_WRITABLE 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_DAT_SYM_INSTALL_DIR SIM_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_DAT_SYM 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_GENERATE_HEX 1
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HAS_BYTE_LANE 0
#define ONCHIP_MEMORY2_0_MEMORY_INFO_HEX_INSTALL_DIR QPF_DIR
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_DATA_WIDTH 64
#define ONCHIP_MEMORY2_0_MEMORY_INFO_MEM_INIT_FILENAME soc_system_onchip_memory2_0

/*
 * Macros for device 'sysid_qsys', class 'altera_avalon_sysid_qsys'
 * The macros are prefixed with 'SYSID_QSYS_'.
 * The prefix is the slave descriptor.
 */
#define SYSID_QSYS_COMPONENT_TYPE altera_avalon_sysid_qsys
#define SYSID_QSYS_COMPONENT_NAME sysid_qsys
#define SYSID_QSYS_BASE 0x10000
#define SYSID_QSYS_SPAN 8
#define SYSID_QSYS_END 0x10007
#define SYSID_QSYS_ID 2899645186
#define SYSID_QSYS_TIMESTAMP 1621964631

/*
 * Macros for device 'avalon_encoder_5', class 'avalon_encoder'
 * The macros are prefixed with 'AVALON_ENCODER_5_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_ENCODER_5_COMPONENT_TYPE avalon_encoder
#define AVALON_ENCODER_5_COMPONENT_NAME avalon_encoder_5
#define AVALON_ENCODER_5_BASE 0x10008
#define AVALON_ENCODER_5_SPAN 8
#define AVALON_ENCODER_5_END 0x1000f

/*
 * Macros for device 'avalon_encoder_4', class 'avalon_encoder'
 * The macros are prefixed with 'AVALON_ENCODER_4_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_ENCODER_4_COMPONENT_TYPE avalon_encoder
#define AVALON_ENCODER_4_COMPONENT_NAME avalon_encoder_4
#define AVALON_ENCODER_4_BASE 0x10010
#define AVALON_ENCODER_4_SPAN 8
#define AVALON_ENCODER_4_END 0x10017

/*
 * Macros for device 'avalon_encoder_3', class 'avalon_encoder'
 * The macros are prefixed with 'AVALON_ENCODER_3_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_ENCODER_3_COMPONENT_TYPE avalon_encoder
#define AVALON_ENCODER_3_COMPONENT_NAME avalon_encoder_3
#define AVALON_ENCODER_3_BASE 0x10018
#define AVALON_ENCODER_3_SPAN 8
#define AVALON_ENCODER_3_END 0x1001f

/*
 * Macros for device 'avalon_encoder_2', class 'avalon_encoder'
 * The macros are prefixed with 'AVALON_ENCODER_2_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_ENCODER_2_COMPONENT_TYPE avalon_encoder
#define AVALON_ENCODER_2_COMPONENT_NAME avalon_encoder_2
#define AVALON_ENCODER_2_BASE 0x10020
#define AVALON_ENCODER_2_SPAN 8
#define AVALON_ENCODER_2_END 0x10027

/*
 * Macros for device 'avalon_encoder_1', class 'avalon_encoder'
 * The macros are prefixed with 'AVALON_ENCODER_1_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_ENCODER_1_COMPONENT_TYPE avalon_encoder
#define AVALON_ENCODER_1_COMPONENT_NAME avalon_encoder_1
#define AVALON_ENCODER_1_BASE 0x10028
#define AVALON_ENCODER_1_SPAN 8
#define AVALON_ENCODER_1_END 0x1002f

/*
 * Macros for device 'avalon_encoder_0', class 'avalon_encoder'
 * The macros are prefixed with 'AVALON_ENCODER_0_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_ENCODER_0_COMPONENT_TYPE avalon_encoder
#define AVALON_ENCODER_0_COMPONENT_NAME avalon_encoder_0
#define AVALON_ENCODER_0_BASE 0x10030
#define AVALON_ENCODER_0_SPAN 8
#define AVALON_ENCODER_0_END 0x10037

/*
 * Macros for device 'avalon_leds_0', class 'avalon_leds'
 * The macros are prefixed with 'AVALON_LEDS_0_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_LEDS_0_COMPONENT_TYPE avalon_leds
#define AVALON_LEDS_0_COMPONENT_NAME avalon_leds_0
#define AVALON_LEDS_0_BASE 0x10068
#define AVALON_LEDS_0_SPAN 8
#define AVALON_LEDS_0_END 0x1006f

/*
 * Macros for device 'dipsw_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'DIPSW_PIO_'.
 * The prefix is the slave descriptor.
 */
#define DIPSW_PIO_COMPONENT_TYPE altera_avalon_pio
#define DIPSW_PIO_COMPONENT_NAME dipsw_pio
#define DIPSW_PIO_BASE 0x10080
#define DIPSW_PIO_SPAN 16
#define DIPSW_PIO_END 0x1008f
#define DIPSW_PIO_IRQ 0
#define DIPSW_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define DIPSW_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define DIPSW_PIO_CAPTURE 1
#define DIPSW_PIO_DATA_WIDTH 4
#define DIPSW_PIO_DO_TEST_BENCH_WIRING 0
#define DIPSW_PIO_DRIVEN_SIM_VALUE 0
#define DIPSW_PIO_EDGE_TYPE ANY
#define DIPSW_PIO_FREQ 50000000
#define DIPSW_PIO_HAS_IN 1
#define DIPSW_PIO_HAS_OUT 0
#define DIPSW_PIO_HAS_TRI 0
#define DIPSW_PIO_IRQ_TYPE EDGE
#define DIPSW_PIO_RESET_VALUE 0

/*
 * Macros for device 'button_pio', class 'altera_avalon_pio'
 * The macros are prefixed with 'BUTTON_PIO_'.
 * The prefix is the slave descriptor.
 */
#define BUTTON_PIO_COMPONENT_TYPE altera_avalon_pio
#define BUTTON_PIO_COMPONENT_NAME button_pio
#define BUTTON_PIO_BASE 0x100c0
#define BUTTON_PIO_SPAN 16
#define BUTTON_PIO_END 0x100cf
#define BUTTON_PIO_IRQ 1
#define BUTTON_PIO_BIT_CLEARING_EDGE_REGISTER 1
#define BUTTON_PIO_BIT_MODIFYING_OUTPUT_REGISTER 0
#define BUTTON_PIO_CAPTURE 1
#define BUTTON_PIO_DATA_WIDTH 4
#define BUTTON_PIO_DO_TEST_BENCH_WIRING 0
#define BUTTON_PIO_DRIVEN_SIM_VALUE 0
#define BUTTON_PIO_EDGE_TYPE FALLING
#define BUTTON_PIO_FREQ 50000000
#define BUTTON_PIO_HAS_IN 1
#define BUTTON_PIO_HAS_OUT 0
#define BUTTON_PIO_HAS_TRI 0
#define BUTTON_PIO_IRQ_TYPE EDGE
#define BUTTON_PIO_RESET_VALUE 0

/*
 * Macros for device 'avalon_control_5', class 'avalon_control'
 * The macros are prefixed with 'AVALON_CONTROL_5_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_CONTROL_5_COMPONENT_TYPE avalon_control
#define AVALON_CONTROL_5_COMPONENT_NAME avalon_control_5
#define AVALON_CONTROL_5_BASE 0x10400
#define AVALON_CONTROL_5_SPAN 1024
#define AVALON_CONTROL_5_END 0x107ff

/*
 * Macros for device 'avalon_control_4', class 'avalon_control'
 * The macros are prefixed with 'AVALON_CONTROL_4_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_CONTROL_4_COMPONENT_TYPE avalon_control
#define AVALON_CONTROL_4_COMPONENT_NAME avalon_control_4
#define AVALON_CONTROL_4_BASE 0x10800
#define AVALON_CONTROL_4_SPAN 1024
#define AVALON_CONTROL_4_END 0x10bff

/*
 * Macros for device 'avalon_control_3', class 'avalon_control'
 * The macros are prefixed with 'AVALON_CONTROL_3_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_CONTROL_3_COMPONENT_TYPE avalon_control
#define AVALON_CONTROL_3_COMPONENT_NAME avalon_control_3
#define AVALON_CONTROL_3_BASE 0x10c00
#define AVALON_CONTROL_3_SPAN 1024
#define AVALON_CONTROL_3_END 0x10fff

/*
 * Macros for device 'avalon_control_2', class 'avalon_control'
 * The macros are prefixed with 'AVALON_CONTROL_2_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_CONTROL_2_COMPONENT_TYPE avalon_control
#define AVALON_CONTROL_2_COMPONENT_NAME avalon_control_2
#define AVALON_CONTROL_2_BASE 0x11000
#define AVALON_CONTROL_2_SPAN 1024
#define AVALON_CONTROL_2_END 0x113ff

/*
 * Macros for device 'avalon_control_1', class 'avalon_control'
 * The macros are prefixed with 'AVALON_CONTROL_1_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_CONTROL_1_COMPONENT_TYPE avalon_control
#define AVALON_CONTROL_1_COMPONENT_NAME avalon_control_1
#define AVALON_CONTROL_1_BASE 0x11400
#define AVALON_CONTROL_1_SPAN 1024
#define AVALON_CONTROL_1_END 0x117ff

/*
 * Macros for device 'avalon_control_0', class 'avalon_control'
 * The macros are prefixed with 'AVALON_CONTROL_0_'.
 * The prefix is the slave descriptor.
 */
#define AVALON_CONTROL_0_COMPONENT_TYPE avalon_control
#define AVALON_CONTROL_0_COMPONENT_NAME avalon_control_0
#define AVALON_CONTROL_0_BASE 0x11800
#define AVALON_CONTROL_0_SPAN 1024
#define AVALON_CONTROL_0_END 0x11bff

/*
 * Macros for device 'jtag_uart', class 'altera_avalon_jtag_uart'
 * The macros are prefixed with 'JTAG_UART_'.
 * The prefix is the slave descriptor.
 */
#define JTAG_UART_COMPONENT_TYPE altera_avalon_jtag_uart
#define JTAG_UART_COMPONENT_NAME jtag_uart
#define JTAG_UART_BASE 0x20000
#define JTAG_UART_SPAN 8
#define JTAG_UART_END 0x20007
#define JTAG_UART_IRQ 2
#define JTAG_UART_READ_DEPTH 64
#define JTAG_UART_READ_THRESHOLD 8
#define JTAG_UART_WRITE_DEPTH 64
#define JTAG_UART_WRITE_THRESHOLD 8


#endif /* _ALTERA_HPS_0_H_ */
