# TCL File Generated by Component Editor 19.1
# Tue May 25 12:41:45 COT 2021
# DO NOT MODIFY


# 
# avalon_control "Avalon Control" v1.0
# Franz Luepke 2021.05.25.12:41:45
# IP component for PID controller with RPM setpoint and PWM output.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_control
# 
set_module_property DESCRIPTION "IP component for PID controller with RPM setpoint and PWM output."
set_module_property NAME avalon_control
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Robocol
set_module_property AUTHOR "Franz Luepke"
set_module_property DISPLAY_NAME "Avalon Control"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_control
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avalon_control.v VERILOG PATH ip/avalon_control/avalon_control.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.compatible dev,avalon-control
set_module_assignment embeddedsw.dts.group control
set_module_assignment embeddedsw.dts.vendor dsa


# 
# display items
# 


# 
# connection point avs_s0
# 
add_interface avs_s0 avalon end
set_interface_property avs_s0 addressUnits WORDS
set_interface_property avs_s0 associatedClock clock
set_interface_property avs_s0 associatedReset reset
set_interface_property avs_s0 bitsPerSymbol 8
set_interface_property avs_s0 bridgedAddressOffset 0
set_interface_property avs_s0 burstOnBurstBoundariesOnly false
set_interface_property avs_s0 burstcountUnits WORDS
set_interface_property avs_s0 explicitAddressSpan 0
set_interface_property avs_s0 holdTime 0
set_interface_property avs_s0 linewrapBursts false
set_interface_property avs_s0 maximumPendingReadTransactions 0
set_interface_property avs_s0 maximumPendingWriteTransactions 0
set_interface_property avs_s0 readLatency 0
set_interface_property avs_s0 readWaitTime 1
set_interface_property avs_s0 setupTime 0
set_interface_property avs_s0 timingUnits Cycles
set_interface_property avs_s0 writeWaitTime 0
set_interface_property avs_s0 ENABLED true
set_interface_property avs_s0 EXPORT_OF ""
set_interface_property avs_s0 PORT_NAME_MAP ""
set_interface_property avs_s0 CMSIS_SVD_VARIABLES ""
set_interface_property avs_s0 SVD_ADDRESS_GROUP ""

add_interface_port avs_s0 avs_s0_address address Input 8
add_interface_port avs_s0 avs_s0_read read Input 1
add_interface_port avs_s0 avs_s0_readdata readdata Output 32
add_interface_port avs_s0 avs_s0_write write Input 1
add_interface_port avs_s0 avs_s0_writedata writedata Input 32
add_interface_port avs_s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment avs_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment avs_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point RPM
# 
add_interface RPM conduit end
set_interface_property RPM associatedClock clock
set_interface_property RPM associatedReset reset
set_interface_property RPM ENABLED true
set_interface_property RPM EXPORT_OF ""
set_interface_property RPM PORT_NAME_MAP ""
set_interface_property RPM CMSIS_SVD_VARIABLES ""
set_interface_property RPM SVD_ADDRESS_GROUP ""

add_interface_port RPM RPM new_signal Output 16


# 
# connection point PWM
# 
add_interface PWM conduit end
set_interface_property PWM associatedClock clock
set_interface_property PWM associatedReset reset
set_interface_property PWM ENABLED true
set_interface_property PWM EXPORT_OF ""
set_interface_property PWM PORT_NAME_MAP ""
set_interface_property PWM CMSIS_SVD_VARIABLES ""
set_interface_property PWM SVD_ADDRESS_GROUP ""

add_interface_port PWM PWM new_signal Input 16


# 
# connection point PID
# 
add_interface PID conduit end
set_interface_property PID associatedClock clock
set_interface_property PID associatedReset reset
set_interface_property PID ENABLED true
set_interface_property PID EXPORT_OF ""
set_interface_property PID PORT_NAME_MAP ""
set_interface_property PID CMSIS_SVD_VARIABLES ""
set_interface_property PID SVD_ADDRESS_GROUP ""

add_interface_port PID KP new_signal Output 16
add_interface_port PID KI new_signal_1 Output 16
add_interface_port PID KD new_signal_2 Output 16


# 
# connection point DIR
# 
add_interface DIR conduit end
set_interface_property DIR associatedClock clock
set_interface_property DIR associatedReset reset
set_interface_property DIR ENABLED true
set_interface_property DIR EXPORT_OF ""
set_interface_property DIR PORT_NAME_MAP ""
set_interface_property DIR CMSIS_SVD_VARIABLES ""
set_interface_property DIR SVD_ADDRESS_GROUP ""

add_interface_port DIR DIR new_signal Input 1

