# TCL File Generated by Component Editor 19.1
# Wed May 26 22:05:46 COT 2021
# DO NOT MODIFY


# 
# avalon_rpm "Avalon RPM" v1.0
# Franz Luepke 2021.05.26.22:05:46
# IP Component to read and write to RPM calculation module.
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_rpm
# 
set_module_property DESCRIPTION "IP Component to read and write to RPM calculation module."
set_module_property NAME avalon_rpm
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Robocol
set_module_property AUTHOR "Franz Luepke"
set_module_property DISPLAY_NAME "Avalon RPM"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_rpm
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file avalon_rpm.v VERILOG PATH ip/avalon_rpm/avalon_rpm.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# module assignments
# 
set_module_assignment embeddedsw.dts.compatible dev,avalon-encoder
set_module_assignment embeddedsw.dts.group encoder
set_module_assignment embeddedsw.dts.vendor dsa


# 
# display items
# 


# 
# connection point avs_s0
# 
add_interface avs_s0 avalon end
set_interface_property avs_s0 addressUnits WORDS
set_interface_property avs_s0 associatedClock clock
set_interface_property avs_s0 associatedReset reset
set_interface_property avs_s0 bitsPerSymbol 8
set_interface_property avs_s0 bridgedAddressOffset 0
set_interface_property avs_s0 burstOnBurstBoundariesOnly false
set_interface_property avs_s0 burstcountUnits WORDS
set_interface_property avs_s0 explicitAddressSpan 0
set_interface_property avs_s0 holdTime 0
set_interface_property avs_s0 linewrapBursts false
set_interface_property avs_s0 maximumPendingReadTransactions 0
set_interface_property avs_s0 maximumPendingWriteTransactions 0
set_interface_property avs_s0 readLatency 0
set_interface_property avs_s0 readWaitTime 1
set_interface_property avs_s0 setupTime 0
set_interface_property avs_s0 timingUnits Cycles
set_interface_property avs_s0 writeWaitTime 0
set_interface_property avs_s0 ENABLED true
set_interface_property avs_s0 EXPORT_OF ""
set_interface_property avs_s0 PORT_NAME_MAP ""
set_interface_property avs_s0 CMSIS_SVD_VARIABLES ""
set_interface_property avs_s0 SVD_ADDRESS_GROUP ""

add_interface_port avs_s0 avs_s0_address address Input 8
add_interface_port avs_s0 avs_s0_read read Input 1
add_interface_port avs_s0 avs_s0_readdata readdata Output 32
add_interface_port avs_s0 avs_s0_write write Input 1
add_interface_port avs_s0 avs_s0_writedata writedata Input 32
add_interface_port avs_s0 avs_s0_waitrequest waitrequest Output 1
set_interface_assignment avs_s0 embeddedsw.configuration.isFlash 0
set_interface_assignment avs_s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avs_s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avs_s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1


# 
# connection point rpm
# 
add_interface rpm conduit end
set_interface_property rpm associatedClock clock
set_interface_property rpm associatedReset ""
set_interface_property rpm ENABLED true
set_interface_property rpm EXPORT_OF ""
set_interface_property rpm PORT_NAME_MAP ""
set_interface_property rpm CMSIS_SVD_VARIABLES ""
set_interface_property rpm SVD_ADDRESS_GROUP ""

add_interface_port rpm rpm new_signal Input 16


# 
# connection point cpr
# 
add_interface cpr conduit end
set_interface_property cpr associatedClock clock
set_interface_property cpr associatedReset ""
set_interface_property cpr ENABLED true
set_interface_property cpr EXPORT_OF ""
set_interface_property cpr PORT_NAME_MAP ""
set_interface_property cpr CMSIS_SVD_VARIABLES ""
set_interface_property cpr SVD_ADDRESS_GROUP ""

add_interface_port cpr cpr new_signal Output 16


# 
# connection point gearhead
# 
add_interface gearhead conduit end
set_interface_property gearhead associatedClock clock
set_interface_property gearhead associatedReset ""
set_interface_property gearhead ENABLED true
set_interface_property gearhead EXPORT_OF ""
set_interface_property gearhead PORT_NAME_MAP ""
set_interface_property gearhead CMSIS_SVD_VARIABLES ""
set_interface_property gearhead SVD_ADDRESS_GROUP ""

add_interface_port gearhead gearhead new_signal Output 16

